name: Pipeline

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: .

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.x

      - name: Get dependencies
        run: |
          yarn

      - name: Test
        run: |
          yarn test

      - name: Lint
        run: |
          yarn lint

      # - name: Upload coverage to Codecov
      #   run: bash <(curl -s https://codecov.io/bash)

  dockerize:
    name: Dockerize
    needs: test
    if: startsWith(github.ref,'refs/tags/v')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Dockerize
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: rkilingr/gorank-frontend:${{ steps.vars.outputs.tag }}
